version: "3"
services:
  client:
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - "3001:3001"
    volumes:
      - ./client:/app/client
    depends_on:
      - server
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    ports:
      - "3002:3002"
    volumes:
      - ./server:/app/server
  nginx:
    container_name: proxy_nginx
    depends_on:
      - client
      - server
    image: nginx:latest
    ports:
      - '81:81'
    volumes:
      - ./nginx:/app/nginx/conf.d
    restart: always
